CREATE SCHEMA IF NOT EXISTS TOP5;

CREATE TABLE IF NOT EXISTS TOP5.USER_FAVOURITE_ARTISTS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    ARTIST_ID BIGINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    LAST_UPDATED_AT DATETIME,
    CONSTRAINT PK_USER_FAVOURITE_ARTISTS_ID PRIMARY KEY (ID),
    UNIQUE (USER_ID, ARTIST_ID)
);

CREATE TABLE IF NOT EXISTS TOP5.ARTISTS (
    ID BIGINT NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    GENRE VARCHAR(255) NOT NULL,
    ALBUMS_LAST_UPDATED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    LAST_UPDATED_AT DATETIME,
    CONSTRAINT PK_ARTISTS_ID PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TOP5.ARTIST_TOP_ALBUMS (
    ID BIGINT NOT NULL,
    ARTIST_ID BIGINT NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    GENRE VARCHAR(255) NOT NULL,
    RELEASED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    LAST_UPDATED_AT DATETIME,
    CONSTRAINT PK_ARTIST_TOP_ALBUMS_ID PRIMARY KEY (ID)
);
